/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PathsRouteImport } from './routes/paths'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IkigaiRouteImport } from './routes/ikigai'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsRoute = PathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IkigaiRoute = IkigaiRouteImport.update({
  id: '/ikigai',
  path: '/ikigai',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkin': typeof CheckinRoute
  '/ikigai': typeof IkigaiRoute
  '/insights': typeof InsightsRoute
  '/paths': typeof PathsRoute
  '/quiz': typeof QuizRoute
  '/stories': typeof StoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkin': typeof CheckinRoute
  '/ikigai': typeof IkigaiRoute
  '/insights': typeof InsightsRoute
  '/paths': typeof PathsRoute
  '/quiz': typeof QuizRoute
  '/stories': typeof StoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkin': typeof CheckinRoute
  '/ikigai': typeof IkigaiRoute
  '/insights': typeof InsightsRoute
  '/paths': typeof PathsRoute
  '/quiz': typeof QuizRoute
  '/stories': typeof StoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/checkin'
    | '/ikigai'
    | '/insights'
    | '/paths'
    | '/quiz'
    | '/stories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/checkin'
    | '/ikigai'
    | '/insights'
    | '/paths'
    | '/quiz'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/checkin'
    | '/ikigai'
    | '/insights'
    | '/paths'
    | '/quiz'
    | '/stories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CheckinRoute: typeof CheckinRoute
  IkigaiRoute: typeof IkigaiRoute
  InsightsRoute: typeof InsightsRoute
  PathsRoute: typeof PathsRoute
  QuizRoute: typeof QuizRoute
  StoriesRoute: typeof StoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths': {
      id: '/paths'
      path: '/paths'
      fullPath: '/paths'
      preLoaderRoute: typeof PathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ikigai': {
      id: '/ikigai'
      path: '/ikigai'
      fullPath: '/ikigai'
      preLoaderRoute: typeof IkigaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CheckinRoute: CheckinRoute,
  IkigaiRoute: IkigaiRoute,
  InsightsRoute: InsightsRoute,
  PathsRoute: PathsRoute,
  QuizRoute: QuizRoute,
  StoriesRoute: StoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
